"""add_review_card_table

Revision ID: f79d82ec6267
Revises: fa093aebfe2f
Create Date: 2026-01-01 01:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79d82ec6267'
down_revision: Union[str, None] = 'fa093aebfe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('COMPLETION', 'REJECTION', 'IN_PROGRESS', 'BLOCKED', 'RECURRING', name='reviewcardtypeenum'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cards_id'), 'review_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_cards_id'), table_name='review_cards')
    op.drop_table('review_cards')
    # ### end Alembic commands ###
