"""Initial schema

Revision ID: fa093aebfe2f
Revises: 
Create Date: 2025-12-30 15:12:05.456735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa093aebfe2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance', sa.Enum('A', 'B', 'C', 'D', name='importanceenum'), nullable=False),
    sa.Column('urgency', sa.Enum('IMMEDIATE', 'SOON', 'CAN_DEFER', 'LONGTERM', name='urgencyenum'), nullable=False),
    sa.Column('state', sa.Enum('READY', 'IN_PROGRESS', 'BLOCKED', 'PARKED', 'COMPLETED', 'CANCELLED', name='taskstateenum'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('recurrence', sa.Enum('NONE', 'DAILY', 'WEEKLY', name='recurrenceenum'), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=255), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_values_id'), 'values', ['id'], unique=False)
    op.create_table('daily_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('priority_date', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_priorities_id'), 'daily_priorities', ['id'], unique=False)
    op.create_table('rejection_dampening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('rejected_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejection_dampening_id'), 'rejection_dampening', ['id'], unique=False)
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_history_id'), 'review_history', ['id'], unique=False)
    op.create_table('task_value_association',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('value_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['values.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_value_association')
    op.drop_index(op.f('ix_review_history_id'), table_name='review_history')
    op.drop_table('review_history')
    op.drop_index(op.f('ix_rejection_dampening_id'), table_name='rejection_dampening')
    op.drop_table('rejection_dampening')
    op.drop_index(op.f('ix_daily_priorities_id'), table_name='daily_priorities')
    op.drop_table('daily_priorities')
    op.drop_index(op.f('ix_values_id'), table_name='values')
    op.drop_table('values')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
